Fix NoClassDefFoundError with Gradle 4.3 or earlier (again).
This bug was fixed in commit 0dd042ca41225c3f2bc58189dca351e19c24725d,
but reappeared after commit 7aeaad407b22958943b5a7f9ed7e1c417bdac89b:
AppPlugin references the new ModelBuilder, making build or sync fail
on older Gradle versions before the plugin can run a version check to
provide a message asking users to update their Gradle version.

This fix slightly decreases code design, but hopefully it's still
acceptable.

Fixes: 73383831
Test: New GradleVersionCheckTest
Change-Id: Ic625489c6121921a6a850f546afaa217a8afc1a0