Revert "Fix tests that needs files from resources in jars"
Build errors:
VmTraceParserTest.java:351:
cannot find symbol
return TestResources.getFile(getClass(), path);

This reverts commit 6c141e2177ace4e1abcc9d4954416c19e12b41c3.

Change-Id: I4b7e4a18745347ed0f4f76dc3818a4b32c1d1833