210052: NoClassDefFoundError when using custom lint jars with inner classes
Remove incorrect optimization. I had assumed that when loading
a top level class it would automatically load the inner classes
so I avoided doing that explicitly, but that is apparently not
the case.

Change-Id: Ida854657f9065c7c6480d6e0dcdd6613009d59c7